### ISSUE TITLE
Gk support termux kah? token nya sama padahal... '-'

### ISSUE THREAD

**Issue by DenisDontol** [AirDropFamilyIDN/BOT-Cube#1]
Gk support termux kah? token nya sama padahal... '-'
![2024-06-02-1642](https://github.com/AirDropFamilyIDN/BOT-Cube/assets/171490922/8c3e2c72-2d21-4fff-886a-f3f438d8fe14)

![ximage_2024-06-02_21-26-19](https://github.com/AirDropFamilyIDN/BOT-Cube/assets/171490922/e8711ae2-b6c8-4108-80f7-39c72cf47c5f)

**Comment by DenisDontol** [comment]
dah fix, typo ternyata gw :v

**Comment by fhatur12** [comment]
kowkowk
